# Generated by Django 4.0.6 on 2022-09-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='persons',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer')], default=1),
        ),
    ]
