# Generated by Django 4.0.6 on 2022-09-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_archivo_alter_persons_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='concursante',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
