# Generated by Django 4.0.6 on 2022-09-27 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_alter_persons_concursante_alter_persons_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(null=True, upload_to='Fotos')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.persons')),
            ],
        ),
    ]
